version: "3.3"

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./composition-api:/app
    command: >
      sh -c "yarn serve"
    environment:
      - CHOKIDAR_USEPOLLING=true
